version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    command: "--keyFile /opt/keyfile/keyfile --replSet=\"terjemah\" && sleep 4 && mongo --eval \"rs.initiate();\""
    volumes:
      - mongodb_data_container:/data/db
      - ./:/opt/keyfile/

volumes:
  mongodb_data_container: